version: '3.8'

networks:
  online-ide:
    external: true
    name: online-ide
    driver: bridge

services:
  ai-engine:
    build:
      context: .
    command: python main.py
    environment:
      - OPENAI_KEY=<your_openai_key_here>
    networks:
      - online-ide
